version: '3'
# docker-compose up
services:
  web:
    container_name: adopt-a-drain
    image: wilfongjt/adopt-a-drain
    build:
      context: ./adopt-a-drain-web/
    command: >
      bash -c "npm install && npm run dev"
    volumes:
      - ./adopt-a-drain-web:/usr/src
    ports:
      - "3000:3000"
